//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.HtmlReporterForAxeCore.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.HtmlReporterForAxeCore.Content.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Url.
        /// </summary>
        public static string HelpUrlRowName {
            get {
                return ResourceManager.GetString("HelpUrlRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string HTMLLabel {
            get {
                return ResourceManager.GetString("HTMLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact.
        /// </summary>
        public static string ImpactRowName {
            get {
                return ResourceManager.GetString("ImpactRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inapplicable.
        /// </summary>
        public static string InapplicableOutcome {
            get {
                return ResourceManager.GetString("InapplicableOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inapplicable.
        /// </summary>
        public static string InapplicableRowName {
            get {
                return ResourceManager.GetString("InapplicableRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string IncompleteOutcome {
            get {
                return ResourceManager.GetString("IncompleteOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string IncompleteRowName {
            get {
                return ResourceManager.GetString("IncompleteRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes.
        /// </summary>
        public static string PassesRowName {
            get {
                return ResourceManager.GetString("PassesRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string PassOutcome {
            get {
                return ResourceManager.GetString("PassOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string RuleHeaderTemplate {
            get {
                return ResourceManager.GetString("RuleHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string RuleOutcomeRowName {
            get {
                return ResourceManager.GetString("RuleOutcomeRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector(s).
        /// </summary>
        public static string SelectorsLabel {
            get {
                return ResourceManager.GetString("SelectorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsRowName {
            get {
                return ResourceManager.GetString("TagsRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test URL.
        /// </summary>
        public static string TestUrlRowName {
            get {
                return ResourceManager.GetString("TestUrlRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string TimestampRowName {
            get {
                return ResourceManager.GetString("TimestampRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Report.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation.
        /// </summary>
        public static string ViolationOutcome {
            get {
                return ResourceManager.GetString("ViolationOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations.
        /// </summary>
        public static string ViolationsRowName {
            get {
                return ResourceManager.GetString("ViolationsRowName", resourceCulture);
            }
        }
    }
}
